application:
  name: SS8_SecurityContext

server:
  port: 8300

spring:
  datasource:
    url: jdbc:mysql://localhost/hello_test8?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update