CREATE TABLE user(
id BIGINT NOT NULL PRIMARY KEY,
username VARCHAR(255),
password VARCHAR(255)
);

CREATE TABLE otp(
id BIGINT NOT NULL PRIMARY KEY,
username VARCHAR(255),
otp VARCHAR(255)
);

CREATE TABLE token(
username VARCHAR(255) PRIMARY KEY,
tokenhash VARCHAR(255)
)